public class LaberintoRecursivo {

        // 0 = Camino libre
            // 1 = Pared
                // 2 = Punto inicial
                    // 3 = Punto final
                        // 9 = Camino correcto

                            static int[][] laberinto = {
                                    {3, 1, 1, 0, 1},
                                            {1, 0, 1, 0, 1},
                                                    {0, 0, 0, 0, 1},
                                                            {0, 1, 1, 0, 1},
                                                                    {0, 0, 1, 2, 0}
                                                                        };

                                                                            static int filas = laberinto.length;
                                                                                static int columnas = laberinto[0].length;

                                                                                    public static void main(String[] args) {

                                                                                            int inicioX = -1;
                                                                                                    int inicioY = -1;

                                                                                                            // Buscar el punto inicial (2)
                                                                                                                    for (int i = 0; i < filas; i++) {
                                                                                                                                for (int j = 0; j < columnas; j++) {
                                                                                                                                                if (laberinto[i][j] == 2) {
                                                                                                                                                                    inicioX = i;
                                                                                                                                                                                        inicioY = j;
                                                                                                                                                                                                        }
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                    if (inicioX == -1) {
                                                                                                                                                                                                                                                System.out.println("No se encontró punto inicial.");
                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                            if (resolver(inicioX, inicioY)) {
                                                                                                                                                                                                                                                                                        System.out.println("Camino encontrado:\n");
                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                            System.out.println("No hay solución.");
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                            mostrar();
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                    // Método recursivo con backtracking
                                                                                                                                                                                                                                                                                                                                        public static boolean resolver(int x, int y) {

                                                                                                                                                                                                                                                                                                                                                // Verificar límites
                                                                                                                                                                                                                                                                                                                                                        if (x < 0 || y < 0 || x >= filas || y >= columnas)
                                                                                                                                                                                                                                                                                                                                                                    return false;

                                                                                                                                                                                                                                                                                                                                                                            // Si es pared o ya visitado
                                                                                                                                                                                                                                                                                                                                                                                    if (laberinto[x][y] == 1 || laberinto[x][y] == 9)
                                                                                                                                                                                                                                                                                                                                                                                                return false;

                                                                                                                                                                                                                                                                                                                                                                                                        // Si es el punto final
                                                                                                                                                                                                                                                                                                                                                                                                                if (laberinto[x][y] == 3)
                                                                                                                                                                                                                                                                                                                                                                                                                            return true;

                                                                                                                                                                                                                                                                                                                                                                                                                                    // Marcar como parte del camino
                                                                                                                                                                                                                                                                                                                                                                                                                                            if (laberinto[x][y] == 0 || laberinto[x][y] == 2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        laberinto[x][y] = 9;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Movimientos (abajo, derecha, arriba, izquierda)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (resolver(x + 1, y) ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    resolver(x, y + 1) ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                resolver(x - 1, y) ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resolver(x, y - 1))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return true;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Backtracking (desmarcar si no sirve)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        laberinto[x][y] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Mostrar el laberinto
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public static void mostrar() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int i = 0; i < filas; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (int j = 0; j < columnas; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.print(laberinto[i][j] + " ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
}