class ArbolBinario {

        // Nodo interno
            class Nodo {
                    int valor;
                            Nodo izquierdo;
                                    Nodo derecho;

                                            Nodo(int valor) {
                                                        this.valor = valor;
                                                                    izquierdo = null;
                                                                                derecho = null;
                                                                                        }
                                                                                            }

                                                                                                private Nodo raiz;

                                                                                                    // Constructor
                                                                                                        public ArbolBinario() {
                                                                                                                raiz = null;
                                                                                                                    }

                                                                                                                        // 🌱 Insertar
                                                                                                                            public void insertar(int valor) {
                                                                                                                                    raiz = insertarRec(raiz, valor);
                                                                                                                                        }

                                                                                                                                            private Nodo insertarRec(Nodo actual, int valor) {
                                                                                                                                                    if (actual == null) {
                                                                                                                                                                return new Nodo(valor);
                                                                                                                                                                        }

                                                                                                                                                                                if (valor < actual.valor) {
                                                                                                                                                                                            actual.izquierdo = insertarRec(actual.izquierdo, valor);
                                                                                                                                                                                                    } else if (valor > actual.valor) {
                                                                                                                                                                                                                actual.derecho = insertarRec(actual.derecho, valor);
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                return actual;
                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                        // 🔍 Buscar
                                                                                                                                                                                                                                            public boolean buscar(int valor) {
                                                                                                                                                                                                                                                    return buscarRec(raiz, valor);
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                            private boolean buscarRec(Nodo actual, int valor) {
                                                                                                                                                                                                                                                                    if (actual == null) return false;

                                                                                                                                                                                                                                                                            if (valor == actual.valor) return true;

                                                                                                                                                                                                                                                                                    if (valor < actual.valor) {
                                                                                                                                                                                                                                                                                                return buscarRec(actual.izquierdo, valor);
                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                    return buscarRec(actual.derecho, valor);
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                    // 🔄 Inorden
                                                                                                                                                                                                                                                                                                                                        public void inorden() {
                                                                                                                                                                                                                                                                                                                                                inordenRec(raiz);
                                                                                                                                                                                                                                                                                                                                                        System.out.println();
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                private void inordenRec(Nodo actual) {
                                                                                                                                                                                                                                                                                                                                                                        if (actual != null) {
                                                                                                                                                                                                                                                                                                                                                                                    inordenRec(actual.izquierdo);
                                                                                                                                                                                                                                                                                                                                                                                                System.out.print(actual.valor + " ");
                                                                                                                                                                                                                                                                                                                                                                                                            inordenRec(actual.derecho);
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                            // 🔄 Preorden
                                                                                                                                                                                                                                                                                                                                                                                                                                public void preorden() {
                                                                                                                                                                                                                                                                                                                                                                                                                                        preordenRec(raiz);
                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println();
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        private void preordenRec(Nodo actual) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (actual != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.print(actual.valor + " ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        preordenRec(actual.izquierdo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    preordenRec(actual.derecho);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 🔄 Postorden
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public void postorden() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                postordenRec(raiz);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                private void postordenRec(Nodo actual) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (actual != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    postordenRec(actual.izquierdo);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                postordenRec(actual.derecho);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.print(actual.valor + " ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
}